default_button: true
default_message: true
default_tab: true
default_tab_edit: true
_core:
  default_config_hash: ffjwyOkkEGJcHRBGwLlGLtdWUcTvXx8Dclcq43MZrT8
button:
  cour: true
  help: false
  docu: false
  spag: true
  tuit: true
  saut: true
  lage: true
message:
  cour: false
  help: false
  docu: false
  spag: true
  tuit: true
  saut: true
  lage: true
tab:
  cour: false
  help: false
  docu: false
  spag: true
  tuit: true
  saut: true
  lage: true
tab_edit:
  cour: false
  help: false
  docu: false
  spag: true
  tuit: true
  saut: true
  lage: true
