minimum_single: 20
minimum_multiple: 20
disable_search_threshold: 0
minimum_width: 0
jquery_selector: 'select:visible'
search_contains: false
disable_search: false
allow_single_deselect: false
placeholder_text_multiple: 'Choose some options'
placeholder_text_single: 'Choose an option'
no_results_text: 'No results match'
disabled_themes:
  seven: '0'
  adminimal_theme: '0'
  wvuonline2018: '0'
chosen_include: 0
_core:
  default_config_hash: JUHKHJeHl1bWXY41HMIcDR-VmAWvJ4OJycDubCkIeDU
