definitions:
  contact__site_page:
    enabled: true
    menu_name: footer
    parent: ''
    weight: 0
    expanded: false
  standard__front_page:
    weight: -42
    menu_name: main
    parent: ''
    enabled: false
    expanded: false
  user__page:
    weight: -37
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
  user__logout:
    weight: -36
    menu_name: account
    parent: ''
    expanded: false
    enabled: true
_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
