module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  adminimal_admin_toolbar: 0
  auto_entitylabel: 0
  automated_cron: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  block_class: 0
  block_visibility_groups: 0
  block_visibility_groups_admin: 0
  breakpoint: 0
  ckeditor: 0
  color: 0
  components: 0
  conditional_fields: 0
  config: 0
  config_direct_save: 0
  config_update: 0
  config_update_ui: 0
  contact: 0
  content_moderation: 0
  content_moderation_notifications: 0
  contextual: 0
  ctools: 0
  ctools_block: 0
  ctools_views: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_enhanced: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_views_select: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  force_password_change: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  layout_discovery: 0
  link: 0
  link_attributes: 0
  linkit: 0
  media: 0
  menu_ui: 0
  metatag: 0
  metatag_facebook: 0
  metatag_favicons: 0
  metatag_google_plus: 0
  metatag_mobile: 0
  metatag_open_graph: 0
  metatag_twitter_cards: 0
  metatag_views: 0
  node: 0
  options: 0
  page_cache: 0
  path: 0
  quickedit: 0
  rabbit_hole: 0
  rdf: 0
  redirect: 0
  responsive_image: 0
  rh_node: 0
  rh_taxonomy: 0
  rh_user: 0
  rules: 0
  scheduler: 0
  search_api: 0
  search_api_db: 0
  settings_tray: 0
  shortcut: 0
  sidr: 0
  simple_sitemap: 0
  slick: 0
  slick_ui: 0
  slick_views: 0
  svg_image_field: 0
  switch_page_theme: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  twig_tweak: 0
  typed_data: 0
  unified_twig_ext: 0
  update: 0
  user: 0
  video_embed_field: 0
  views_ui: 0
  workflows: 0
  extlink: 1
  menu_link_content: 1
  pathauto: 1
  views: 10
  standard: 1000
theme:
  stable: 0
  classy: 0
  seven: 0
  adminimal_theme: 0
  wvuonline2018: 0
profile: standard
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
